install:
  # Download Meteor
  - ps: Start-FileDownload 'https://s3.amazonaws.com/meteor-windows/InstallMeteor.exe'
  # Install meteor
  - .\InstallMeteor.exe /passive
  # Restart
  - ps: Start-Sleep -s 5
  - ps: Restart-Computer -Force

build: off

cache:
  - '%HOMEPATH%\AppData\Local\.meteor'

test_script:
  - cd C:\projects\rocket-chat
  - meteor.bat build
